project:
  type: website
  output-dir: _site

website:
  title: "Math 558 · Foundations of Mathematics"
  sidebar:
    style: "floating"
    search: true
    background: light
    contents:
      - href: index.qmd
        text: Home
      - href: lectures/lec01.qmd
        text: "1 · Some History and Setting the Stage"
      - href: lectures/lec02.qmd
        text: "2 · The Foundational Crisis"
      - href: notes/zfc-as-a-foundation.qmd
        text: "3 · ZFC as a Foundational Theory"
      - href: notes/first-consequences.qmd
        text: "4 · First Consequences of the ZFC Axioms"
      - href: notes/relations-and-functions.qmd
        text: "5 · Relations and Functions"
      - href: notes/ordinals.qmd
        text: "6 · Ordinals"
      - href: notes/recursion.qmd
        text: "7 · Induction and Recursion"
      - href: notes/AC.qmd
        text: "8 · Axiom of Choice"
      - href: notes/cardinals.qmd
        text: "9 · Cardinals"

  page-footer:
    left: "Math 558 · Foundations of Mathematics · Penn State"

format:
  html:
    theme: [cosmo, custom.scss]
    callout-icon: false
    filters:
      - callouty-theorem
    toc: true
    toc-depth: 3
    number-sections: false
    html-math-method: mathjax
    grid:
      body-width: 820px
  revealjs:
    theme: [serif, custom.scss]
    slide-number: c/t
    transition: fade
    incremental: false
    footer: "Math 558 · Foundations of Mathematics"


callouty-theorem:
  thm:
    override-title: false # do not override the title of the callout (title won't show when `appearance` set to `simple` or `minimal`)
    callout: # parameters of the wrapping callout. see Quarto documentation of callouts for more details
      type: warning
      appearance: simple
    
  prp:
    override-title: false
    callout:
      type: caution
      appearance: minimal

  lem:
    override-title: false
    callout:
      type: caution
      appearance: minimal

  remark:
    override-title: false
    callout:
      type: tip
      appearance: simple
  
  exr:
    override-title: false
    callout:
      type: tip
      appearance: simple

  proof: # also support wrapping proof-like environments
    override-title: true # override the title of the callout by the name of the theorem
    callout:
      type: note
      appearance: simple
      collapse: true
      icon: true

  solution:
    override-title: true
    callout:
      type: note
      appearance: default
      collapse: true
      icon: true

  cor: 
     override-title: false 
     callout: 
      type: caution
      appearance: simple
    
  def:
    override-title: false
    callout: 
      type: note
      appearance: simple

  exm:
    override-title: false
    callout: 
      type: tip
      appearance: simple
